### ISSUE TITLE
More info please :)

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/minercantile#1]
What does this mod do? Some info in the readme would be helpful.
:large_orange_diamond:

**Comment by Cyberpangolin** [comment]
Indeed! :+1: 

As I had the original idea, I hope I can write the readme soon. For now, what I can tell you in a short way (i don't have much time ATM):

This mod aims to make a big centralised store, where any ressource can be sold / bought, with an automatised way to make evolve price: a rare ressource costs lots of money, and a very frequent one becomes cheaper and cheaper.
Another proprietey of this mod: A rare ressource that is never traded gains in value with time, because all prices depend on the stock of money into the shop and it tends to grow with time. Actually the shop always takes more money than gives and has limitations on how much items you can buy / sell at once to make sure you can never gain money by buying - then selling - a same ressource.
Last but not least: to have money, you have to change the coins you find naturally ingame at the bancomatic, and then it's stored into your wallet.

A big thanks to @crabman77 who patiently tried to understand the idea and implementing it

I hope it's enough for now.

If you wish more details, you can find them here: https://github.com/MinetestForFun/server-minetestforfun/issues/436 BUT sadly in french. Sorry, I wanted to be perfectly understood and did not feel confident enough to explain it in english. Writing the readme fils should not be that difficult though.

**Comment by Cyberpangolin** [comment]
Ok, now we have a basic readme file, I close the ticket.
